name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn docs/v1:build
          yarn docs/v2:build
          mkdir -p docs/.vitepress/dist
          cp -r docs/v1/.vitepress/dist/* docs/.vitepress/dist/v1/
          cp -r docs/v2/.vitepress/dist/* docs/.vitepress/dist/v2/
          cp index.html docs/.vitepress/dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LAGRANGEDOCACTION }}
          publish_dir: docs/.vitepress/dist